trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'RaptorSA'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: Dockerfile